# ---------------------------------------------------------------------------
# IMLAB
# ---------------------------------------------------------------------------

stages:
    - build
    - test

build_debug:
    stage: build
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja
    cache:
        key: "$CI_COMMIT_REF_NAME-debug"
        paths:
            - build/
        policy: pull-push
    artifacts:
        paths:
            - ./build/tester
            - ./build/tester_schema
        expire_in: 1 hrs
    tags:
        - "clang-6.0"
        - "llvm-6.0"
        - "cmake"
        - "python3"

tester:
    stage: test
    script:
        - ./build/tester --gtest_filter=-DatabaseQueryTest.AnalyticalQuery*
    dependencies:
        - build_debug
    tags:
        - "clang-6.0"
        - "llvm-6.0"
        - "cmake"
        - "python3"

cpplint:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        - ninja lint
    allow_failure: true
    tags:
        - "clang-6.0"
        - "llvm-6.0"
        - "cmake"
        - "python3"
